### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by amiyuy** [Didstopia/fetchforge#43]
I downloaded the first 544 clips fine, but it errored at 545 and the time just keeps increasing.  I tried restarting it.

```
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\snapshot\fetchforge\node_modules\node-fetch\lib\index.js:1284:9)
    at fetch.isRedirect (C:\snapshot\fetchforge\node_modules\node-fetch\lib\index.js:1370:19)
    at new Promise (<anonymous>)
    at fetch (C:\snapshot\fetchforge\node_modules\node-fetch\lib\index.js:1367:9)
    at R2._request (C:\snapshot\fetchforge\node_modules\r2\index.js:85:12)
    at constructor.response.Promise.resolve.then (C:\snapshot\fetchforge\node_modules\r2\index.js:47:55)
    at <anonymous>
```

Username: amiyuy

Downloading clip 545 out of 640 (85%) - Time keeps increasing

Cache file: https://www.dropbox.com/s/lj45e6oywekf7s5/2018-07-31_apollo-cache-persist?dl=0

Also broke when downloading my husband's clips: toreltwiddler

78 out of 89

**Comment by Dids** [comment]
If possible, could you run it once again, but this time from the command line/command prompt, like this: ```fetchforge-win.exe --verbose```

This should (hopefully) print much more information on what file/url it's failing at, so I can see about getting it fixed.

I'm also running it locally in verbose mode using your husband's username, but that seems like it'll take a while.

**Comment by Dids** [comment]
Found the issue! Pushing out a fix momentarily.

**Comment by Dids** [comment]
https://github.com/Didstopia/fetchforge/releases/tag/v0.1.7
